version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: yes
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: ec2-user
    mode: 664
    type:
      - file
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: ec2-user
    mode: 775
    type:
      - directory
  - object: /var/www/html/scripts
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/setup_environment.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_apache.sh
      timeout: 300
      runas: root
      
