version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y zip

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Build started on `date`

  build:
    commands:
      - echo Entered the build phase...
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Creating deployment package...

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - terraform/**/*
    - deployment/**/*
    - .git/**/*
    - .gitignore
    - readme.md
    - .idea/**/*
    - .php_cs.cache