name: Trufflehog-Trial

on:
  push:
    branches:
      - master-test
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog Actions Scan
        uses: shraddha-jiem/trufflehog-actions-scan@master
        with: 
          scanArguments: "--regex --max_depth=10 --rules /regexes.json"
      

      